version: '3.8'

services:

  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local